### ISSUE TITLE
Add to Laravel Requests Rules

### ISSUE THREAD

**Issue by werner-h** [aman00323/email-checker#13]
Why not add your functionality to the Laravel requests rule?

For example: 
`'email' => 'required|email|check_disposable',`
`'email' => 'required|email|check_mx_dns',`
`'email' => 'required|email|check_domain_status',`
`'email' => 'required|email|check_email',`

**Comment by aman00323** [comment]
@werner-h  I know we can do this, it is on my to do list. Right now i am occupied in my routine work, If you are available then please contribute.
