### ISSUE TITLE
Most of the time we get `500: Internal Server Error` from gist.githubusercontent.com

### ISSUE THREAD

**Issue by mobinzk** [aman00323/email-checker#15]
**Describe the bug**
Most of the time we get `500: Internal Server Error` from gist.githubusercontent.com. 
Would be good if we had the ability to have those lists with in the repo and look them up within our project/server.

For example, today Github's server went down and this causing issue on the websites using this package as it has dependancy on github gist.

**Screenshots**

<img width="1259" alt="Screenshot 2020-04-23 at 14 21 09" src="https://user-images.githubusercontent.com/2981528/80104373-cff41c80-856e-11ea-9f8f-4177108e6caa.png">

**Comment by aman00323** [comment]
Okay @mobinzk , will do a feature upgrade where package will able to clone from gist, when ever user need to update list. this might solve problem.

I was expecting gist to be immutable

**Comment by mobinzk** [comment]
@aman00323 Thanks for your kind reply, that would be awesome. Let me know if I can be any help on this.

**Comment by aman00323** [comment]
@mobinzk It would be great if you want to contribute, I may not be able update package instantly, because i am occupied in my day to day work.

What we have to do is
- Change path in Helper.php (to local path)
- Create folder `directory`.
- Write a command that will clone all files from gist to that directory.
- Command should be exported while publishing package facade.

I will be happy if you contribute, let me know if you need any help

**Comment by mobinzk** [comment]
Sure thing, I'll give it a go.

**Comment by mobinzk** [comment]
Could you please give me some direction on `Command should be exported while publishing package facade` ?
Not sure how this should work and where I need to call the command.

**Comment by aman00323** [comment]
@mobinzk You can follow this step

https://github.com/aman00323/email-checker/blob/master/src/EmailCheckerServiceProvider.php#L28

inside boot() write below code

```php
$this->publishes([
            __DIR__ . '/Command/GetDisposableEmail.php' => base_path().'/Console/Commands/GetDisposableEmail.php',
        ]);
```

**Comment by mobinzk** [comment]
I see, am I right saying this code will then make a copy of the command to the project Command directory and then user needs to run the command manually to get the domain list?

So after installing the composer user needs to run the following two commands?
```
php artisan vendor:publish // To get the command file
```

```
php artisan Get:DisposableEmailDomains // to get the list of domains in to the Storage folder of the user's project
```

Am I understanding this correctly? 
How do you think we should make it backwards compatible? 
Do you think it's a good idea to have the gist URL as the backup so if the user doesn't have the files it still works with gist URLs.

**Comment by aman00323** [comment]
@mobinzk I was thinking same, we should do backward compatible. 

I was thinking drop plan to build command, instead of we will do local files available instead of gist.

**Comment by mobinzk** [comment]
So we include the gist files in the repo?

**Comment by aman00323** [comment]
@mobinzk Exactly

**Comment by aman00323** [comment]
@mobinzk released https://github.com/aman00323/email-checker/releases/tag/2.2.0
