### ISSUE TITLE
I've realised the DNS/MX checker doesn't work with hotmail

### ISSUE THREAD

**Issue by mobinzk** [aman00323/email-checker#19]
**Describe the bug**
I've realised the DNS/MX checker doesn't work with hotmail. Thought to report it here for reference.

**Comment by aman00323** [comment]
Thank you @mobinzk for reporting issue, can you post here more details. What kind of response we are getting for hotmail.

There was issue that was reported https://github.com/aman00323/email-checker/issues/18 but it may occur while doing rapid request.

Please post more info then we can figure it out.

**Comment by aman00323** [comment]
@mobinzk  ^^
